# -*- coding: utf-8 -*-
"""Main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vpCUISxrm03zJXLejPETXRL46Om36K9a
"""



# @title VROMLIX GENESIS: COGNITIVE ORCHESTRATOR v8.3
"""
VROMLIX GENESIS (v8.3)
======================
Enterprise Cognitive ETL Pipeline for Knowledge Graph Construction.
Refactored for strict PEP 8 compliance, Type Safety (Py3.12+), and Architectural Robustness.

ORIGINAL AUTHOR: Rogelio Lozano
REFACTORED BY: Vromlix (System Architecture)
DATE: 2026-01-26

USAGE:
    python vromlix.py --run-all --verbose
    python vromlix.py --only-indexing
"""

import argparse
import ast
import csv
import hashlib
import json
import logging
import math
import os
import re
import shutil
import sys
import time
import xml.etree.ElementTree as ET
from dataclasses import asdict, dataclass, field
from datetime import datetime
from enum import StrEnum
from pathlib import Path
from tempfile import NamedTemporaryFile
from typing import Any, Generator, Optional, Protocol, runtime_checkable, override, Final

# --- SAFEGUARD: CONDITIONAL IMPORTS ---
# We use a facade pattern to prevent crashes if libs are missing.
try:
    import numpy as np
    import faiss  # type: ignore
    from sentence_transformers import SentenceTransformer  # type: ignore
    HAS_VECTOR_SUPPORT = True
except ImportError:
    HAS_VECTOR_SUPPORT = False

try:
    from google import genai
    from google.genai import types
    from google.colab import userdata  # type: ignore
    HAS_GOOGLE_SDK = True
except ImportError:
    HAS_GOOGLE_SDK = False

# ==============================================================================
# 1. TYPE DEFINITIONS & CONFIGURATION (THE CONTRACT)
# ==============================================================================

class VromlixError(Exception):
    """Root exception for known domain errors."""

class ConfigurationError(VromlixError):
    """Raised when critical config is missing."""

class IntegrityError(VromlixError):
    """Raised when data validation fails."""

class LogLevel(StrEnum):
    DEBUG = "DEBUG"
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"

@dataclass(frozen=True)
class AppConfig:
    """
    Immutable System Configuration.
    Acts as the Single Source of Truth for paths and constants.
    """
    system_version: str = "8.3.1"

    # AI Parameters
    agent_model: str = "gemma-3-27b-it"  # Optimized for speed/cost
    system_model: str = "gemini-3-flash-preview" # Optimized for logic
    temperature: float = 0.0

    # Rate Limiting
    max_tpm: int = 14_000
    rotation_buffer_sec: float = 61.0

    # File System
    root_dir: Path = field(default_factory=lambda: Path("/content/drive/MyDrive/00_VROMLIX_ECOSYSTEM"))

    @property
    def input_dir(self) -> Path: return self.root_dir / "00_input_tray"
    @property
    def memory_dir(self) -> Path: return self.root_dir / "01_active_memory"
    @property
    def ledger_file(self) -> Path: return self.memory_dir / "06_deep_memory.jsonl"
    @property
    def profile_file(self) -> Path: return self.memory_dir / "00_dynamic_profile.xml"
    @property
    def index_file(self) -> Path: return self.memory_dir / "02_master_index.csv"

    def validate_environment(self) -> None:
        """Fail-fast check for critical paths."""
        if not self.root_dir.exists() and not os.getenv("VROMLIX_TEST_MODE"):
            logging.warning(f"Root dir {self.root_dir} not found. Attempting creation...")
            try:
                self.ensure_directories()
            except OSError as e:
                raise ConfigurationError(f"Cannot create root structure: {e}")

    def ensure_directories(self) -> None:
        """Idempotent directory creation."""
        for p in [self.input_dir, self.memory_dir]:
            p.mkdir(parents=True, exist_ok=True)

@dataclass
class ChatEntry:
    """
    Data Transfer Object for Memory Entries.
    Enforces strict typing for the JSONL ledger.
    """
    id_hash: str
    origin_date: str
    full_content: str
    title: str
    assigned_category: str
    quality_score: str
    temporal_inference: str
    executive_summary: str
    ingestion_timestamp: str
    vromlix_dimensions: dict[str, Any]
    latent_connections: Optional[list[dict[str, Any]]] = None
    xml_relevant_insight: str = ""

    def to_json(self) -> str:
        """Serialization with UTF-8 enforcement."""
        return json.dumps(asdict(self), ensure_ascii=False)

# ==============================================================================
# 2. UTILITIES & SAFEGUARDS (THE TOOLS)
# ==============================================================================

class SafeIO:
    """
    Encapsulates dangerous I/O operations with atomic guarantees.
    Prevents partial writes.
    """
    @staticmethod
    def atomic_write(target_path: Path, content: str, mode: str = 'w') -> None:
        """Writes to a temp file first, then renames to target."""
        target_path.parent.mkdir(parents=True, exist_ok=True)
        # Create temp file in the same directory to ensure atomic move works
        tmp_name = f"{target_path.name}.tmp"
        tmp_path = target_path.parent / tmp_name

        try:
            with open(tmp_path, mode, encoding='utf-8') as f:
                f.write(content)
            # Atomic replacement
            shutil.move(str(tmp_path), str(target_path))
        except Exception as e:
            if tmp_path.exists():
                os.remove(tmp_path)
            logging.error(f"Atomic write failed for {target_path}: {e}")
            raise IOError(f"Failed to write {target_path}") from e

    @staticmethod
    def safe_append(target_path: Path, line: str) -> None:
        """Appends a line safely with flushing."""
        try:
            with open(target_path, 'a', encoding='utf-8') as f:
                f.write(line + '\n')
        except IOError as e:
            logging.error(f"Append failed for {target_path}: {e}")
            raise

class RobustParser:
    """
    Legacy-compatible parser.
    Preserves the 'dirty' extraction logic but wraps it safely.
    """
    @staticmethod
    def clean_ui_garbage(text: str) -> str:
        """Removes UI artifacts."""
        pattern = re.compile(r"expand_more|content_copy|^python$|^copy code$|^Pesta\u00f1a \d+", re.I | re.M)
        lines = [line for line in text.split('\n') if not pattern.search(line.strip())]
        return "\n".join(lines).strip()

    @staticmethod
    def extract_json(text: str | None) -> dict[str, Any]:
        """
        Extracts JSON from mixed text.
        SECURITY FIX: Replaced raw eval() with ast.literal_eval().
        """
        if not text: return {}

        # 1. Try Direct Parse
        try:
            return json.loads(text)
        except json.JSONDecodeError:
            pass

        # 2. Try Regex Extraction
        match = re.search(r'(\{[\s\S]*\})', text)
        if match:
            json_str = match.group()
            try:
                return json.loads(json_str)
            except json.JSONDecodeError:
                # 3. Last Resort: Python Literal Eval (Sanitized)
                # This handles cases where JSON is actually a Python dict string (Single quotes, None, True/False)
                try:
                    sanitized = (json_str
                                 .replace("true", "True")
                                 .replace("false", "False")
                                 .replace("null", "None"))
                    val = ast.literal_eval(sanitized)
                    if isinstance(val, dict):
                        return val
                except (ValueError, SyntaxError):
                    logging.debug(f"Failed to parse JSON/Dict from text: {text[:50]}...")

        return {}

    @staticmethod
    def safe_join(data: list | str | None) -> str:
        """Flattens mixed lists into a string."""
        if not data: return ""
        if isinstance(data, str): return data
        clean_items = []
        for item in data:
            if isinstance(item, str):
                clean_items.append(item)
            elif isinstance(item, dict):
                # Heuristic: Find the most 'value-like' key
                val = next((v for k, v in item.items() if k in {'name', 'tool', 'value', 'model'}), str(item))
                clean_items.append(str(val))
            else:
                clean_items.append(str(item))
        return ", ".join(clean_items)

# ==============================================================================
# 3. CORE LOGIC & API ADAPTERS
# ==============================================================================

@runtime_checkable
class LLMClientProtocol(Protocol):
    def generate(self, model: str, prompt: str) -> str | None: ...

class TokenBucket:
    """
    Rate Limiter.
    PRESERVED LOGIC: Fixed window reset (every 60s).
    """
    def __init__(self, limit: int) -> None:
        self.limit = limit
        self.used = 0
        self.start_time = time.time()

    def can_consume(self, cost: int) -> bool:
        self._refresh()
        return (self.used + cost) <= self.limit

    def consume(self, cost: int) -> None:
        self._refresh()
        self.used += cost

    def _refresh(self) -> None:
        now = time.time()
        # Logic Warning: This creates a fixed window, not sliding. Preserved per "Chesterton's Fence".
        if now - self.start_time > 60:
            self.start_time = now
            self.used = 0

class GoogleGenAIAdapter(LLMClientProtocol):
    """
    Manages API Keys and Requests.
    Implements Round-Robin rotation.
    """
    def __init__(self, config: AppConfig):
        self.config = config
        self.keys: list[str] = self._discover_keys()
        self.clients: dict[int, Any] = {}
        self.buckets: dict[int, TokenBucket] = {}
        self.current_idx = 0

        if not self.keys:
            logging.warning("No GOOGLE_API_KEYs found. LLM features will be disabled.")
        else:
            self._init_clients()

    def _discover_keys(self) -> list[str]:
        """Scans Env and Userdata for keys following pattern GOOGLE_API_KEY_XX."""
        candidates = ['GOOGLE_API_KEY'] + [f'GOOGLE_API_KEY_{i:02d}' for i in range(1, 20)]
        found = []

        # Check OS Env
        for k in candidates:
            v = os.getenv(k)
            if v and v not in found: found.append(v)

        # Check Colab Userdata
        if HAS_GOOGLE_SDK:
            try:
                for k in candidates:
                    try:
                        v = userdata.get(k)
                        if v and v not in found: found.append(v)
                    except Exception: continue
            except AttributeError: pass

        return found

    def _init_clients(self) -> None:
        if not HAS_GOOGLE_SDK: return
        for i, key in enumerate(self.keys):
            try:
                self.clients[i] = genai.Client(api_key=key)
                self.buckets[i] = TokenBucket(self.config.max_tpm)
            except Exception as e:
                logging.error(f"Failed to init client {i}: {e}")

    def _get_active_client(self, estimated_tokens: int) -> Any:
        """
        Selects a client with available quota.
        If all full, blocks until current key refreshes.
        """
        if not self.clients: return None

        # Try finding a free key
        start_idx = self.current_idx
        for _ in range(len(self.keys)):
            bucket = self.buckets[self.current_idx]
            if bucket.can_consume(estimated_tokens):
                bucket.consume(estimated_tokens)
                return self.clients[self.current_idx]

            # Rotate
            logging.info(f"Key {self.current_idx} saturated. Rotating...")
            self.current_idx = (self.current_idx + 1) % len(self.keys)

        # Fallback: Wait
        logging.warning("All keys saturated. Entering wait state...")
        bucket = self.buckets[self.current_idx]
        wait_time = 61.0 - (time.time() - bucket.start_time)
        if wait_time > 0:
            time.sleep(wait_time)
        bucket.consume(estimated_tokens)
        return self.clients[self.current_idx]

    @override
    def generate(self, model: str, prompt: str) -> str | None:
        if not self.clients: return None

        est_tokens = (len(prompt) // 4) + 500
        client = self._get_active_client(est_tokens)

        # Safety Settings: Unrestricted for creative analysis
        safety_settings = [
            types.SafetySetting(category=cat, threshold="BLOCK_NONE")
            for cat in ["HARM_CATEGORY_HATE_SPEECH", "HARM_CATEGORY_SEXUALLY_EXPLICIT",
                        "HARM_CATEGORY_DANGEROUS_CONTENT", "HARM_CATEGORY_HARASSMENT"]
        ]

        for attempt in range(3):
            try:
                response = client.models.generate_content(
                    model=model,
                    contents=prompt,
                    config=types.GenerateContentConfig(
                        temperature=self.config.temperature,
                        safety_settings=safety_settings
                    )
                )
                return response.text if response.text else None
            except Exception as e:
                err_msg = str(e)
                if "429" in err_msg or "400" in err_msg:
                    logging.warning(f"API Error ({err_msg[:30]}). Rotating key.")
                    self.current_idx = (self.current_idx + 1) % len(self.keys)
                    client = self.clients[self.current_idx]
                    time.sleep(1)
                else:
                    logging.error(f"Fatal GenAI Error: {e}")
                    return None
        return None

# ==============================================================================
# 4. BUSINESS DOMAIN SERVICES
# ==============================================================================

class RefineryService:
    """
    Ingestion Engine.
    Responsible for transforming raw text into structured ChatEntries.
    """

    # PROMPTS (FROZEN to ensure semantic stability)
    AGENTS: Final[dict[str, str]] = {
        "CRONOS": """ROLE: TIME KEEPER.\nTASK: Extract the LATEST date (YYYY-MM-DD) from the IN content.\nOUTPUT_FORMAT: Respond SOLELY with a JSON object adhering to the provided schema.\nJSON_SCHEMA: {"type": "object", "properties": {"final_timestamp": {"type": "string", "format": "date", "description": "The LATEST date found in the text in YYYY-MM-DD format."}}, "required": ["final_timestamp"]}\nIN:""",
        "SYNTHESIZER": """ROLE: EXECUTIVE SUMMARY GENERATOR.\nTASK: Generate a concise title, an executive summary, and determine the status (CURRENT|LEGACY) based on the IN content.\nOUTPUT_FORMAT: Respond SOLELY with a JSON object adhering to the provided schema.\nJSON_SCHEMA: {"type": "object", "properties": {"title": {"type": "string", "description": "A concise title for the content."}, "summary": {"type": "string", "description": "An executive summary of the content."}, "status": {"type": "string", "enum": ["CURRENT", "LEGACY"], "description": "Indicates if the content is current or legacy."}}, "required": ["title", "summary", "status"]}\nIN:""",
        "NARRATIVE": "ROLE: NARRATIVE ARCHIVIST. JSON {'narrative_context': 'String', 'atmosphere': 'String'}",
        "CLASSIFIER": "ROLE: CATEGORIZER. Context: {cats}. JSON {'suggested_category': 'String'}",
        "LOGOS": "ROLE: BELIEF EXTRACTOR. JSON {'mental_models': [str], 'beliefs': [str]}",
        "PATHOS": "ROLE: EMOTION SENSOR. JSON {'tone': 'String', 'anchors': [str]}",
        "TECHNE": "ROLE: TOOL EXTRACTOR. JSON {'tools': [str], 'solutions': [str]}",
        "POIESIS": "ROLE: MUSE. JSON {'references': [str], 'aesthetics': [str]}",
        "GEM": "ROLE: ANOMALY HUNTER. JSON {'gems': [str], 'trivia': [str]}",
        "INSIGHT_ENGINE": "ROLE: INSIGHT ARCHITECT. TASK: Analyze the provided 'dimensions' JSON. Synthesize a SINGLE, DENSE sentence identifying strictly NEW skills, beliefs, or goals demonstrated by Roger. IGNORE trivial chat. OUTPUT: Raw text string only. No JSON."
    }

    def __init__(self, config: AppConfig, llm: LLMClientProtocol):
        self.config = config
        self.llm = llm
        self.known_hashes = self._load_history()

    def _load_history(self) -> set[str]:
        hashes = set()
        if self.config.ledger_file.exists():
            try:
                with open(self.config.ledger_file, 'r', encoding='utf-8') as f:
                    for line in f:
                        if not line.strip(): continue
                        try:
                            entry = json.loads(line)
                            hashes.add(entry.get('id_hash'))
                        except json.JSONDecodeError: continue
            except IOError as e:
                logging.error(f"Could not read ledger: {e}")
        return hashes

    def process_inbox(self) -> None:
        files = list(self.config.input_dir.glob("*.txt"))
        logging.info(f"Refinery: Processing {len(files)} files.")

        splitter = re.compile(r"(?:##\s*)?(?:Chat|CHAT):\s*.*?|\n(?=Pesta\u00f1a \d+)", re.I | re.DOTALL)

        for file_path in files:
            self._process_file(file_path, splitter)

    def _process_file(self, path: Path, splitter: re.Pattern) -> None:
        try:
            content = path.read_text(encoding='utf-8', errors='ignore')
        except IOError as e:
            logging.error(f"Read Error {path.name}: {e}")
            return

        fragments = [f.strip() for f in splitter.split(content) if f.strip()] or [content.strip()]

        for raw_frag in fragments:
            clean_text = RobustParser.clean_ui_garbage(raw_frag)
            if len(clean_text) < 50: continue

            content_hash = hashlib.md5(clean_text.encode()).hexdigest()
            if content_hash in self.known_hashes:
                continue

            entry = self._synthesize_entry(content_hash, clean_text)
            if entry:
                SafeIO.safe_append(self.config.ledger_file, entry.to_json())
                self.known_hashes.add(entry.id_hash)
                logging.info(f"Ingested: {entry.id_hash[:8]} | {entry.title}")

    def _synthesize_entry(self, uid: str, text: str) -> ChatEntry | None:
        """
        Orchestrates the multi-agent analysis pipeline.
        Returns None if critical metadata (Date/Title) cannot be extracted.
        """
        current_quality_score = "3"

        # 1. CRONOS (Critical: Date)
        cronos_prompt = f"{self.AGENTS['CRONOS']}{text[:10000]}"
        c_resp = self.llm.generate(self.config.agent_model, cronos_prompt)
        c_data = RobustParser.extract_json(c_resp)

        if not c_data.get("final_timestamp"):
            logging.warning(f"Skip {uid[:8]}: No Date extracted.")
            return None

        # 2. SYNTHESIZER (Critical: Summary)
        synthesizer_prompt = f"{self.AGENTS['SYNTHESIZER']}{text[:20000]}"
        s_resp = self.llm.generate(self.config.agent_model, synthesizer_prompt)
        s_data = RobustParser.extract_json(s_resp)

        if not s_data.get("title") or not s_data.get("summary"):
            s_data = {"title": "Untitled (Parse Error)", "summary": "Automatic summary failed.", "status": "CURRENT"}
            current_quality_score = "2"

        # 3. DIMENSIONS (Optional but valuable)
        dims = {}

        # Narrative
        n_resp = self.llm.generate(self.config.agent_model, f"{self.AGENTS['NARRATIVE']}\nIN:\n{text[:20000]}")
        n_data = RobustParser.extract_json(n_resp)
        dims['narrative'] = n_data if n_data else {"narrative_context": "Failed", "atmosphere": "Unknown"}

        # Classifier
        try:
            cats = "['General', 'Philosophy', 'Engineering', 'Strategy', 'Science', 'Entertainment']"
            cl_resp = self.llm.generate(self.config.agent_model, self.AGENTS['CLASSIFIER'].format(cats=cats) + f"\nIN:\n{text[:5000]}")
            assigned_category = RobustParser.extract_json(cl_resp).get("suggested_category", "General")
        except Exception:
            assigned_category = "General"

        # Parallel-ish Extraction
        for agent_key in ["LOGOS", "PATHOS", "TECHNE", "POIESIS", "GEM"]:
            try:
                resp = self.llm.generate(self.config.agent_model, f"{self.AGENTS[agent_key]}\nIN:\n{text[:15000]}")
                dims[agent_key.lower()] = RobustParser.extract_json(resp)
            except Exception:
                dims[agent_key.lower()] = {}

        # 4. INSIGHT (The "So What?")
        relevant_insight = ""
        try:
            insight_prompt = f"{self.AGENTS['INSIGHT_ENGINE']}\nDIMENSIONS_CONTEXT: {json.dumps(dims, ensure_ascii=False)}"
            insight_raw = self.llm.generate(self.config.agent_model, insight_prompt)
            relevant_insight = RobustParser.clean_ui_garbage(insight_raw) if insight_raw else ""

            # Logic Preserved: Downgrade score if insight fails, unless already bad.
            if not relevant_insight and current_quality_score != "1":
                current_quality_score = "2"
        except Exception:
            relevant_insight = "Insight generation failed."

        return ChatEntry(
            id_hash=uid,
            origin_date=c_data.get("final_timestamp", datetime.now().strftime("%Y-%m-%d")),
            full_content=text,
            title=s_data.get("title", "Untitled"),
            assigned_category=assigned_category,
            quality_score=current_quality_score,
            temporal_inference=s_data.get("status", "CURRENT"),
            executive_summary=s_data.get("summary", "No summary"),
            ingestion_timestamp=datetime.now().isoformat(),
            vromlix_dimensions=dims,
            xml_relevant_insight=relevant_insight
        )

class MirrorService:
    """
    Module 2: XML Profile Surgery.
    Maintains the Dynamic Profile XML file based on new evidence.
    """
    DEFAULT_SKELETON = """<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<vromlix_profile version="8.1">
    <system_kernel>
        <identity name="VROMLIX" base_version="8.3"/>
    </system_kernel>
    <user_context identity="Roger">
        </user_context>
    <dynamic_patches>
        </dynamic_patches>
</vromlix_profile>"""

    def __init__(self, config: AppConfig, llm: LLMClientProtocol):
        self.config = config
        self.llm = llm

    def run_surgery(self) -> None:
        if not self.config.ledger_file.exists(): return

        self._ensure_profile()
        evidence = self._gather_evidence()
        if not evidence: return

        current_patches = self._read_patches()

        prompt = f"""
        ROLE: MEMORY SURGEON (System State Updater).
        TASK: EVOLVE 'Dynamic Patches' XML based on NEW EVIDENCE using a CONSERVATIVE MERGE STRATEGY.

        INPUTS:
        1. CURRENT_XML: The existing profile.
        2. NEW_EVIDENCE: Recent insights.

        RULES:
        - PRESERVE: Do NOT delete existing static data unless strictly contradicted.
        - UPDATE: Add new skills to <tech_stack>, update beliefs.
        - FORMAT: Return ONLY the content inside <dynamic_patches>.

        CURRENT_XML:
        {current_patches}

        NEW_EVIDENCE:
        {evidence}
        """

        resp = self.llm.generate(self.config.system_model, prompt)
        if resp and "NO_CHANGES" not in resp:
            self._apply_patch(resp)

    def _ensure_profile(self) -> None:
        if not self.config.profile_file.exists():
            SafeIO.atomic_write(self.config.profile_file, self.DEFAULT_SKELETON)

    def _read_patches(self) -> str:
        try:
            tree = ET.parse(self.config.profile_file)
            root = tree.getroot()
            context_nodes = []
            for tag in ["active_status", "cognitive_model"]:
                node = root.find(tag)
                if node is not None:
                    context_nodes.append(ET.tostring(node, encoding='unicode'))
            
            patches_node = root.find("dynamic_patches")
            patches_str = "".join([ET.tostring(c, encoding='unicode') for c in patches_node]) if patches_node is not None else ""
            
            return "\n".join(context_nodes) + "\n<dynamic_patches>\n" + patches_str + "\n</dynamic_patches>"
        except ET.ParseError:
            return ""

    def _gather_evidence(self) -> str:
        """Reads last 200 entries to form context."""
        lines = []
        try:
            with open(self.config.ledger_file, 'r', encoding='utf-8') as f:
                all_logs = f.readlines()

            targets = all_logs[-200:]
            for line in targets:
                try:
                    d = json.loads(line)
                    insight = d.get('xml_relevant_insight', '').strip()
                    date = d.get('origin_date', 'Unknown')

                    if len(insight) > 10:
                        lines.append(f"[{date}] INSIGHT: {insight}")
                    else:
                        summary = d.get('executive_summary', '')[:100]
                        lines.append(f"[{date}] SUM: {summary}")
                except json.JSONDecodeError: continue
        except IOError: pass
        return "\n".join(lines)

    def _apply_patch(self, xml_fragment: str) -> None:
        """Parses and atomically updates the XML file."""
        try:
            # Clean Markdown blocks
            clean = xml_fragment.replace("```xml", "").replace("```", "").strip()
            # Wrap in dummy root to parse fragments
            new_nodes = ET.fromstring(f"<r>{clean}</r>")

            tree = ET.parse(self.config.profile_file)
            root = tree.getroot()
            patches = root.find("dynamic_patches")
            if patches is None:
                patches = ET.SubElement(root, "dynamic_patches")

            patches.clear()
            for child in new_nodes:
                patches.append(child)

            # Atomic Write via temp string -> SafeIO
            xml_str = ET.tostring(root, encoding='unicode')
            SafeIO.atomic_write(self.config.profile_file, xml_str)
            logging.info("Mirror Surgery: Profile Updated.")

        except ET.ParseError as e:
            logging.error(f"Surgery Failed (XML Parse): {e}. Fragment: {xml_fragment[:50]}...")

class IndexingService:
    """
    Module 3: FAISS Vector Indexing.
    """
    def __init__(self, config: AppConfig):
        self.config = config

    def rebuild_index(self) -> None:
        if not HAS_VECTOR_SUPPORT:
            logging.warning("Vector dependencies missing. Skipping Indexing.")
            return

        if not self.config.ledger_file.exists(): return

        entries = []
        try:
            with open(self.config.ledger_file, 'r', encoding='utf-8') as f:
                for l in f:
                    try: entries.append(json.loads(l))
                    except json.JSONDecodeError: continue
        except IOError: return

        if not entries: return

        # Prepare Text for Embedding
        texts = []
        for e in entries:
            dims = e.get('vromlix_dimensions', {})
            insight = e.get('xml_relevant_insight', '')

            # Safe access to nested dicts
            narrative = dims.get('narrative', {}).get('narrative_context', '')
            tools_list = dims.get('techne', {}).get('tools', [])
            tools_str = RobustParser.safe_join(tools_list)

            text = (
                f"TITLE: {e['title']}. "
                f"INSIGHT: {insight}. "
                f"SUM: {e['executive_summary']}. "
                f"WHY: {narrative}. "
                f"TOOLS: {tools_str}."
            )
            texts.append(text)

        logging.info(f"Generating Embeddings for {len(texts)} entries...")
        model = SentenceTransformer('all-MiniLM-L6-v2')
        embeddings = model.encode(texts)

        # FAISS Indexing
        index = faiss.IndexFlatIP(embeddings.shape[1])
        faiss.normalize_L2(embeddings.astype('float32'))
        index.add(embeddings.astype('float32'))

        self._write_csv_and_update_links(entries, index, embeddings)

    def _write_csv_and_update_links(self, entries: list[dict], index: Any, embeddings: Any) -> None:
        D, I = index.search(embeddings.astype('float32'), k=6)

        updated_ledger = []

        # Write CSV
        try:
            with open(self.config.index_file, 'w', newline='', encoding='utf-8') as csvfile:
                writer = csv.writer(csvfile)
                writer.writerow(["ID", "Date", "Category", "Title", "Summary", "Context", "Connections"])

                for idx, entry in enumerate(entries):
                    # Find Latent Connections
                    links = []
                    for rank, neighbor_idx in enumerate(I[idx]):
                        if idx != neighbor_idx and D[idx][rank] > 0.65:
                            neighbor = entries[neighbor_idx]
                            links.append({
                                "id": neighbor['id_hash'],
                                "title": neighbor['title'],
                                "score": float(D[idx][rank])
                            })

                    entry['latent_connections'] = links[:5]
                    updated_ledger.append(json.dumps(entry, ensure_ascii=False))

                    dims = entry.get('vromlix_dimensions', {})
                    narrative = dims.get('narrative', {}).get('narrative_context', '')[:100]
                    conn_str = ";".join([l['title'] for l in links[:3]])

                    writer.writerow([
                        entry['id_hash'][:8],
                        entry['origin_date'],
                        entry['assigned_category'],
                        entry['title'],
                        entry['executive_summary'],
                        narrative,
                        conn_str
                    ])

        except IOError as e:
            logging.error(f"Failed to write CSV index: {e}")
            return

        # Update Ledger with new connections
        try:
            SafeIO.atomic_write(self.config.ledger_file, '\n'.join(updated_ledger))
            logging.info("Indexing Complete & Ledger Updated.")
        except IOError as e:
            logging.error(f"Failed to update ledger with connections: {e}")

class MaintenanceService:
    """
    Module 4: Sanitation & Hygiene.
    Responsible for keeping the Deep Memory ledger clean and consistent.
    """
    def __init__(self, config: AppConfig):
        self.config = config

    def run_sanitation(self) -> None:
        """
        Scans the ledger for malformed or failed entries ('Untitled', 'No summary')
        and purges them to maintain high-quality vector retrieval.
        """
        if not self.config.ledger_file.exists():
            logging.info("Maintenance: Ledger not found. Nothing to clean.")
            return

        logging.info("Maintenance: Starting Sanitation Protocol...")

        valid_entries = []
        removed_count = 0
        total_count = 0

        # PASS 1: READ & FILTER
        try:
            with open(self.config.ledger_file, 'r', encoding='utf-8') as f:
                for line in f:
                    if not line.strip(): continue
                    total_count += 1
                    try:
                        entry = json.loads(line)

                        # CRITERIA FOR PURGE (The "Bad Data" Signature)
                        is_untitled = entry.get('title') == "Untitled"
                        is_failed_summary = entry.get('executive_summary') == "No summary"
                        has_no_id = not entry.get('id_hash')

                        if is_untitled or is_failed_summary or has_no_id:
                            removed_count += 1
                            # Log sample of deleted data for audit
                            snippet = entry.get('id_hash', 'NO_ID')[:8]
                            logging.debug(f"Purging invalid entry: {snippet}")
                        else:
                            valid_entries.append(line.strip())

                    except json.JSONDecodeError:
                        logging.warning(f"Purging corrupt JSON line: {line[:50]}...")
                        removed_count += 1
                        continue
        except IOError as e:
            logging.error(f"Maintenance Failed (Read): {e}")
            return

        # PASS 2: ATOMIC WRITE (Safety First)
        if removed_count > 0:
            try:
                # Reconstruct the file content
                new_content = "\n".join(valid_entries) + "\n" # Ensure trailing newline
                SafeIO.atomic_write(self.config.ledger_file, new_content)
                logging.info(f"Sanitation Complete. Removed {removed_count} of {total_count} entries.")
            except Exception as e:
                logging.error(f"Maintenance Failed (Write): {e}")
        else:
            logging.info("Sanitation Complete. System is clean.")

# ==============================================================================
# 5. ORCHESTRATOR & CLI
# ==============================================================================

class VromlixOrchestrator:
    def __init__(self, config: AppConfig):
        self.config = config
        self.config.ensure_directories()

        logging.basicConfig(
            level=logging.INFO,
            format='%(asctime)s - [VROMLIX] - %(levelname)s - %(message)s',
            force=True
        )

    def run(self, stages: list[str]) -> None:
        logging.info(f"BOOTING VROMLIX {self.config.system_version}")

        # Mount Drive Check
        if Path("/content").exists() and not Path("/content/drive").exists():
            try:
                from google.colab import drive # type: ignore
                drive.mount("/content/drive")
            except ImportError:
                logging.warning("Colab Drive mount failed or not needed.")

        llm_client = GoogleGenAIAdapter(self.config)

        if "refinery" in stages:
            RefineryService(self.config, llm_client).process_inbox()

        if "mirror" in stages:
            MirrorService(self.config, llm_client).run_surgery()

        if "sanitize" in stages:
            MaintenanceService(self.config).run_sanitation()

        if "index" in stages:
            IndexingService(self.config).rebuild_index()

def main() -> None:
    parser = argparse.ArgumentParser(description="VROMLIX GENESIS: Cognitive Orchestrator")
    parser.add_argument("--run-all", action="store_true", help="Run full pipeline")
    parser.add_argument("--refinery", action="store_true", help="Run Ingestion only")
    parser.add_argument("--mirror", action="store_true", help="Run Profile Surgery only")
    parser.add_argument("--index", action="store_true", help="Run Indexing only")
    parser.add_argument("--dry-run", action="store_true", help="Simulate execution without writes (Not fully impl)")
    parser.add_argument("--sanitize", action="store_true", help="Run Ledger Sanitation (Remove failed entries)")

    args, unknown = parser.parse_known_args()

    stages = []
    if args.run_all or (not any([args.refinery, args.mirror, args.index])):
        stages = ["refinery", "mirror", "index"]
    else:
        if args.refinery: stages.append("refinery")
        if args.mirror: stages.append("mirror")
        if args.index: stages.append("index")
        if args.sanitize: stages.append("sanitize")

    config = AppConfig()
    try:
        config.validate_environment()
        VromlixOrchestrator(config).run(stages)
    except KeyboardInterrupt:
        logging.warning("Execution interrupted by user.")
        sys.exit(130)
    except Exception as e:
        logging.critical(f"SYSTEM HALT: {e}", exc_info=True)
        sys.exit(1)

if __name__ == "__main__":
    main()
