# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N6bd_FJjylQCawo70S6jXR3wan061irm
"""

# Instalación de librerías críticas para VROMLIX v8.0
!pip install -U google-genai sentence-transformers faiss-cpu numpy

# @title VROMLIX GENESIS: COGNITIVE ORCHESTRATOR v8.0
"""
VROMLIX GENESIS (v8.0)
======================
Enterprise Cognitive ETL Pipeline for Knowledge Graph Construction.
Refactored for strict PEP 8 compliance, Type Safety (Py3.12+), and Architectural Robustness.

ORIGINAL AUTHOR: Rogelio Lozano
REFACTORED BY: NEXUS (System Architecture)
DATE: 2026-01-24

USAGE:
    python vromlix.py --run-all --verbose
    python vromlix.py --only-indexing
"""

import argparse
import csv
import glob
import hashlib
import json
import logging
import math
import os
import re
import sys
import time
import xml.etree.ElementTree as ET
from dataclasses import asdict, dataclass, field
from datetime import datetime
from enum import StrEnum, auto
from pathlib import Path
from typing import Any, Generator, Iterator, Optional, Protocol, Self, runtime_checkable, override

# --- CONDITIONAL IMPORTS (Graceful Degradation) ---
try:
    import numpy as np
    import faiss  # type: ignore
    from sentence_transformers import SentenceTransformer  # type: ignore
    HAS_VECTOR_SUPPORT = True
except ImportError:
    HAS_VECTOR_SUPPORT = False

try:
    from google import genai
    from google.genai import types
    from google.colab import userdata  # type: ignore
    HAS_GOOGLE_SDK = True
except ImportError:
    HAS_GOOGLE_SDK = False

# ==============================================================================
# 1. CORE TYPES & CONFIGURATION
# ==============================================================================

class VromlixError(Exception):
    """Base exception for Vromlix ecosystem."""

class ResourceExhaustedError(VromlixError):
    """Raised when all API keys are saturated."""

class DataIngestionError(VromlixError):
    """Raised when input data is malformed."""

class LogLevel(StrEnum):
    DEBUG = "DEBUG"
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"

@dataclass(frozen=True)
class AppConfig:
    """Immutable Configuration Object."""
    system_version: str = "8.0.0"
    # Models
    agent_model: str = "gemma-3-27b-it"
    system_model: str = "gemini-3-flash-preview"
    temperature: float = 0.0

    # Limits
    max_tpm: int = 14_000
    rotation_buffer_sec: float = 61.0

    # Paths (Defaults relative to execution, overridable)
    root_dir: Path = field(default_factory=lambda: Path("/content/drive/MyDrive/00_VROMLIX_ECOSYSTEM"))

    @property
    def input_dir(self) -> Path: return self.root_dir / "00_input_tray"

    @property
    def memory_dir(self) -> Path: return self.root_dir / "01_active_memory"

    @property
    def ledger_file(self) -> Path: return self.memory_dir / "06_deep_memory.jsonl"

    @property
    def profile_file(self) -> Path: return self.memory_dir / "00_dynamic_profile.xml"

    @property
    def index_file(self) -> Path: return self.memory_dir / "02_master_index.csv"

    def ensure_directories(self) -> None:
        """Idempotent directory creation."""
        for p in [self.input_dir, self.memory_dir]:
            p.mkdir(parents=True, exist_ok=True)

@dataclass
class ChatEntry:
    """DTO for a processed interaction."""
    id_hash: str
    origin_date: str
    full_content: str
    title: str
    assigned_category: str
    quality_score: str
    temporal_inference: str
    executive_summary: str
    ingestion_timestamp: str
    vromlix_dimensions: dict[str, Any]
    latent_connections: list[dict[str, Any]] | None = None

    def to_json(self) -> str:
        return json.dumps(asdict(self), ensure_ascii=False)

# ==============================================================================
# 2. ABSTRACTIONS & INTERFACES
# ==============================================================================

@runtime_checkable
class LLMClientProtocol(Protocol):
    """Protocol for LLM interactions to allow mocking/swapping."""
    def generate(self, model: str, prompt: str) -> str | None: ...

class TokenBucket:
    """
    Rate Limiter implementing the Token Bucket algorithm.
    Used for proactive API Key rotation.
    """
    def __init__(self, limit: int) -> None:
        self.limit = limit
        self.used = 0
        self.start_time = time.time()

    def can_consume(self, cost: int) -> bool:
        self._refresh()
        return (self.used + cost) <= self.limit

    def consume(self, cost: int) -> None:
        self._refresh()
        self.used += cost

    def _refresh(self) -> None:
        now = time.time()
        if now - self.start_time > 60:
            self.start_time = now
            self.used = 0

class RobustParser:
    """
    Utilities for extracting structured data from 'dirty' LLM outputs.
    Preserves the 'Universal Parsing' logic from legacy v7.5.
    """
    @staticmethod
    def clean_ui_garbage(text: str) -> str:
        """Removes UI artifacts like 'Copy code', 'expand_more'."""
        pattern = re.compile(r"expand_more|content_copy|^python$|^copy code$|^Pesta\u00f1a \d+", re.I | re.M)
        lines = [line for line in text.split('\n') if not pattern.search(line.strip())]
        return "\n".join(lines).strip()

    @staticmethod
    def extract_json(text: str | None) -> dict[str, Any]:
        """Aggressive JSON extraction using Regex fallback."""
        if not text: return {}
        try:
            return json.loads(text)
        except json.JSONDecodeError:
            match = re.search(r'\{.*\}', text, re.DOTALL)
            if match:
                try:
                    return json.loads(match.group())
                except json.JSONDecodeError:
                    # Last resort: Sanitized eval (Legacy fallback)
                    try:
                        sanitized = match.group().replace("true", "True").replace("false", "False").replace("null", "None")
                        # Safety check before eval: only literals
                        # This is risky but required by legacy 'Universal Parsing' spec.
                        # In a stricter environment, we would use ast.literal_eval
                        import ast
                        val = ast.literal_eval(sanitized)
                        if isinstance(val, dict): return val
                    except Exception:
                        pass
        return {}

    @staticmethod
    def safe_join(data: list | str | None) -> str:
        """Flattens mixed lists into a comma-separated string."""
        if not data: return ""
        if isinstance(data, str): return data
        clean_items = []
        for item in data:
            if isinstance(item, str):
                clean_items.append(item)
            elif isinstance(item, dict):
                # Heuristic extraction
                val = next((v for k, v in item.items() if k in {'name', 'tool', 'value', 'model'}), str(item))
                clean_items.append(str(val))
            else:
                clean_items.append(str(item))
        return ", ".join(clean_items)

# ==============================================================================
# 3. INFRASTRUCTURE IMPLEMENTATION
# ==============================================================================

class GoogleGenAIAdapter(LLMClientProtocol):
    """
    Concrete implementation using the `google-genai` SDK.
    Manages key rotation and rate limits.
    """
    def __init__(self, config: AppConfig):
        self.config = config
        self.keys: list[str] = self._discover_keys()
        self.clients: dict[int, Any] = {} # Key Index -> Client
        self.buckets: dict[int, TokenBucket] = {}
        self.current_idx = 0

        if not self.keys:
            logging.warning("No GOOGLE_API_KEYs found. LLM features will fail.")
        else:
            self._init_clients()

    def _discover_keys(self) -> list[str]:
        """Scans environment/userdata for keys."""
        candidates = ['GOOGLE_API_KEY'] + [f'GOOGLE_API_KEY_{i:02d}' for i in range(1, 20)]
        found = []

        # 1. Try OS Env
        for k in candidates:
            v = os.getenv(k)
            if v and v not in found: found.append(v)

        # 2. Try Colab Userdata if available
        if not found and HAS_GOOGLE_SDK:
            try:
                for k in candidates:
                    try:
                        v = userdata.get(k)
                        if v and v not in found: found.append(v)
                    except Exception: continue
            except AttributeError: pass

        return found

    def _init_clients(self) -> None:
        if not HAS_GOOGLE_SDK:
             logging.error("google-genai SDK not installed.")
             return

        for i, key in enumerate(self.keys):
            try:
                self.clients[i] = genai.Client(api_key=key)
                self.buckets[i] = TokenBucket(self.config.max_tpm)
            except Exception as e:
                logging.error(f"Failed to init client {i}: {e}")

    def _get_active_client(self, estimated_tokens: int) -> Any:
        """Key Rotation Logic."""
        start_idx = self.current_idx

        # 1. Search for available key
        for _ in range(len(self.keys)):
            bucket = self.buckets[self.current_idx]
            if bucket.can_consume(estimated_tokens):
                bucket.consume(estimated_tokens)
                return self.clients[self.current_idx]

            # Rotate
            logging.info(f"Key {self.current_idx} saturated. Rotating...")
            self.current_idx = (self.current_idx + 1) % len(self.keys)

        # 2. Fallback: Wait on current key
        logging.warning("All keys saturated. Waiting for capacity...")
        bucket = self.buckets[self.current_idx]
        wait_time = 61.0 - (time.time() - bucket.start_time)
        if wait_time > 0:
            time.sleep(wait_time)
        bucket.consume(estimated_tokens)
        return self.clients[self.current_idx]

    @override
    def generate(self, model: str, prompt: str) -> str | None:
        if not self.clients: return None

        est_tokens = (len(prompt) // 4) + 500
        client = self._get_active_client(est_tokens)

        # Uncensored Safety Config
        safety_settings = [
            types.SafetySetting(category=cat, threshold="BLOCK_NONE")
            for cat in ["HARM_CATEGORY_HATE_SPEECH", "HARM_CATEGORY_SEXUALLY_EXPLICIT",
                        "HARM_CATEGORY_DANGEROUS_CONTENT", "HARM_CATEGORY_HARASSMENT"]
        ]

        for attempt in range(3):
            try:
                response = client.models.generate_content(
                    model=model,
                    contents=prompt,
                    config=types.GenerateContentConfig(
                        temperature=self.config.temperature,
                        safety_settings=safety_settings
                    )
                )
                if response.text:
                    return response.text
                return None
            except Exception as e:
                err_msg = str(e)
                if "429" in err_msg or "400" in err_msg:
                    logging.warning(f"API Error ({err_msg[:30]}). Rotating key.")
                    self.current_idx = (self.current_idx + 1) % len(self.keys)
                    client = self.clients[self.current_idx] # Update client ref
                    time.sleep(1)
                else:
                    logging.error(f"Fatal GenAI Error: {e}")
                    return None
        return None

# ==============================================================================
# 4. BUSINESS LOGIC SERVICES
# ==============================================================================

class RefineryService:
    """Module 1: Ingestion & Metadata Extraction."""

    AGENTS = {
        "CRONOS": "ROLE: TIME KEEPER. TASK: Extract LATEST date (YYYY-MM-DD). JSON {'final_timestamp': 'YYYY-MM-DD'}",
        "SYNTHESIZER": "ROLE: EXECUTIVE SUMMARY. JSON {'title': 'String', 'summary': 'String', 'status': 'CURRENT|LEGACY'}",
        "NARRATIVE": "ROLE: NARRATIVE ARCHIVIST. JSON {'narrative_context': 'String', 'atmosphere': 'String'}",
        "CLASSIFIER": "ROLE: CATEGORIZER. Context: {cats}. JSON {'suggested_category': 'String'}",
        "LOGOS": "ROLE: BELIEF EXTRACTOR. JSON {'mental_models': [str], 'beliefs': [str]}",
        "PATHOS": "ROLE: EMOTION SENSOR. JSON {'tone': 'String', 'anchors': [str]}",
        "TECHNE": "ROLE: TOOL EXTRACTOR. JSON {'tools': [str], 'solutions': [str]}",
        "POIESIS": "ROLE: MUSE. JSON {'references': [str], 'aesthetics': [str]}",
        "GEM": "ROLE: ANOMALY HUNTER. JSON {'gems': [str], 'trivia': [str]}"
    }

    def __init__(self, config: AppConfig, llm: LLMClientProtocol):
        self.config = config
        self.llm = llm
        self.known_hashes = self._load_history()

    def _load_history(self) -> set[str]:
        hashes = set()
        if self.config.ledger_file.exists():
            with open(self.config.ledger_file, 'r', encoding='utf-8') as f:
                for line in f:
                    try:
                        entry = json.loads(line)
                        hashes.add(entry.get('id_hash'))
                    except: continue
        return hashes

    def process_inbox(self) -> None:
        files = list(self.config.input_dir.glob("*.txt"))
        logging.info(f"Refinery: {len(files)} files in tray.")

        splitter = re.compile(r"(?:##\s*)?(?:Chat|CHAT):\s*.*?|\n(?=Pesta\u00f1a \d+)", re.I | re.DOTALL)

        for file_path in files:
            self._process_file(file_path, splitter)

    def _process_file(self, path: Path, splitter: re.Pattern) -> None:
        try:
            content = path.read_text(encoding='utf-8', errors='ignore')
        except Exception as e:
            logging.error(f"Read Error {path.name}: {e}")
            return

        fragments = [f.strip() for f in splitter.split(content) if f.strip()] or [content.strip()]

        for raw_frag in fragments:
            clean_text = RobustParser.clean_ui_garbage(raw_frag)
            if len(clean_text) < 50: continue

            content_hash = hashlib.md5(clean_text.encode()).hexdigest()
            if content_hash in self.known_hashes:
                continue

            entry = self._synthesize_entry(content_hash, clean_text)
            if entry:
                self._persist(entry)

    def _synthesize_entry(self, uid: str, text: str) -> ChatEntry | None:
        # 1. Cronos (Critical)
        c_resp = self.llm.generate(self.config.agent_model, f"{self.AGENTS['CRONOS']}\nIN:\n{text[:10000]}")
        c_data = RobustParser.extract_json(c_resp)
        if not c_data.get("final_timestamp"):
            logging.warning(f"Skip {uid[:8]}: No Date extracted.")
            return None

        # 2. Synthesis & Narrative
        s_resp = self.llm.generate(self.config.agent_model, f"{self.AGENTS['SYNTHESIZER']}\nIN:\n{text[:20000]}")
        n_resp = self.llm.generate(self.config.agent_model, f"{self.AGENTS['NARRATIVE']}\nIN:\n{text[:20000]}")
        s_data = RobustParser.extract_json(s_resp)
        n_data = RobustParser.extract_json(n_resp)

        meta = {**c_data, **s_data}

        # 3. Dimensions
        dims = {'narrative': n_data}
        # Classifier
        try:
            cats = "['General', 'Philosophy', 'Engineering', 'Strategy', 'Science', 'Entertainment']"
            cl_resp = self.llm.generate(self.config.agent_model, self.AGENTS['CLASSIFIER'].format(cats=cats) + f"\nIN:\n{text[:5000]}")
            meta["cat"] = RobustParser.extract_json(cl_resp).get("suggested_category", "General")
        except: meta["cat"] = "General"

        for agent_key in ["LOGOS", "PATHOS", "TECHNE", "POIESIS", "GEM"]:
            resp = self.llm.generate(self.config.agent_model, f"{self.AGENTS[agent_key]}\nIN:\n{text[:15000]}")
            dims[agent_key.lower()] = RobustParser.extract_json(resp)

        return ChatEntry(
            id_hash=uid,
            origin_date=meta.get("final_timestamp", datetime.now().strftime("%Y-%m-%d")),
            full_content=text,
            title=meta.get("title", "Untitled"),
            assigned_category=meta.get("cat", "General"),
            quality_score="3",
            temporal_inference=meta.get("status", "CURRENT"),
            executive_summary=meta.get("summary", "No summary"),
            ingestion_timestamp=datetime.now().isoformat(),
            vromlix_dimensions=dims
        )

    def _persist(self, entry: ChatEntry) -> None:
        with open(self.config.ledger_file, 'a', encoding='utf-8') as f:
            f.write(entry.to_json() + '\n')
        self.known_hashes.add(entry.id_hash)
        logging.info(f"Ingested: {entry.id_hash[:8]} | {entry.title}")

class MirrorService:
    """Module 2: XML Profile Surgery."""

    DEFAULT_SKELETON = """<?xml version="1.0" encoding="UTF-8"?>
<vromlix_profile>
    <static_kernel>
        <identity><name>VROMLIX</name><version>8.0</version></identity>
    </static_kernel>
    <dynamic_patches></dynamic_patches>
</vromlix_profile>"""

    def __init__(self, config: AppConfig, llm: LLMClientProtocol):
        self.config = config
        self.llm = llm

    def run_surgery(self) -> None:
        if not self.config.ledger_file.exists(): return

        self._ensure_profile()
        evidence = self._gather_evidence()
        if not evidence: return

        current_patches = self._read_patches()

        prompt = f"""
        ROLE: MEMORY SURGEON (System State Updater).
        TASK: Evolve 'Dynamic Patches' XML based on new evidence.
        CONTEXT:
        {current_patches}

        NEW EVIDENCE:
        {evidence}

        OUTPUT: Provide ONLY the valid XML content inside <dynamic_patches>.
        If no change needed, return NO_CHANGES.
        """

        resp = self.llm.generate(self.config.system_model, prompt)
        if resp and "NO_CHANGES" not in resp:
            self._apply_patch(resp)

    def _ensure_profile(self) -> None:
        if not self.config.profile_file.exists():
            self.config.profile_file.write_text(self.DEFAULT_SKELETON)

    def _read_patches(self) -> str:
        try:
            tree = ET.parse(self.config.profile_file)
            root = tree.getroot()
            node = root.find("dynamic_patches")
            return "".join([ET.tostring(c, encoding='unicode') for c in node]) if node is not None else ""
        except Exception:
            return ""

    def _gather_evidence(self) -> str:
        lines = []
        try:
            with open(self.config.ledger_file, 'r', encoding='utf-8') as f:
                all_logs = f.readlines()

            # Logic: Priority records + last 20
            targets = []
            for l in all_logs:
                if "PRIORITY" in l or "FUNDACIONAL" in l: targets.append(l)
            targets.extend(all_logs[-20:])

            for line in targets:
                d = json.loads(line)
                dims = d.get('vromlix_dimensions', {})
                tools = RobustParser.safe_join(dims.get('techne', {}).get('tools'))
                beliefs = RobustParser.safe_join(dims.get('logos', {}).get('mental_models'))
                lines.append(f"DATE:{d['origin_date']} | SUM:{d['executive_summary']} | TOOLS:{tools} | BELIEFS:{beliefs}")
        except Exception: pass
        return "\n".join(lines[-30:]) # Limit token usage

    def _apply_patch(self, xml_fragment: str) -> None:
        try:
            # Clean Markdown blocks
            clean = xml_fragment.replace("```xml", "").replace("```", "").strip()
            new_nodes = ET.fromstring(f"<r>{clean}</r>")

            tree = ET.parse(self.config.profile_file)
            root = tree.getroot()
            patches = root.find("dynamic_patches")
            if patches is None: patches = ET.SubElement(root, "dynamic_patches")

            patches.clear()
            for child in new_nodes: patches.append(child)

            tree.write(self.config.profile_file, encoding='unicode')
            logging.info("Mirror Surgery: Profile Updated.")
        except ET.ParseError as e:
            logging.error(f"Surgery Failed (XML Parse): {e}")

class IndexingService:
    """Module 3: FAISS Vector Indexing."""

    def __init__(self, config: AppConfig):
        self.config = config

    def rebuild_index(self) -> None:
        if not HAS_VECTOR_SUPPORT:
            logging.warning("Vector dependencies missing. Skipping Indexing.")
            return

        if not self.config.ledger_file.exists(): return

        entries = []
        with open(self.config.ledger_file, 'r', encoding='utf-8') as f:
            for l in f:
                try: entries.append(json.loads(l))
                except: continue

        if not entries: return

        # Prepare Text
        texts = []
        for e in entries:
            dims = e.get('vromlix_dimensions', {})
            text = (
                f"TITLE: {e['title']}. SUM: {e['executive_summary']}. "
                f"WHY: {dims.get('narrative', {}).get('narrative_context', '')}. "
                f"TOOLS: {RobustParser.safe_join(dims.get('techne', {}).get('tools'))}."
            )
            texts.append(text)

        logging.info("Generating Embeddings...")
        model = SentenceTransformer('all-MiniLM-L6-v2')
        embeddings = model.encode(texts)

        # FAISS
        index = faiss.IndexFlatIP(embeddings.shape[1])
        faiss.normalize_L2(embeddings.astype('float32'))
        index.add(embeddings.astype('float32'))

        # Write CSV & Update Ledger Links
        self._write_csv_and_update_links(entries, index, embeddings)

    def _write_csv_and_update_links(self, entries: list[dict], index: Any, embeddings: Any) -> None:
        D, I = index.search(embeddings.astype('float32'), k=6)

        updated_ledger = []
        with open(self.config.index_file, 'w', newline='', encoding='utf-8') as csvfile:
            writer = csv.writer(csvfile)
            writer.writerow(["ID", "Date", "Category", "Title", "Summary", "Context", "Connections"])

            for idx, entry in enumerate(entries):
                # Find Connections
                links = []
                for rank, neighbor_idx in enumerate(I[idx]):
                    if idx != neighbor_idx and D[idx][rank] > 0.65:
                        neighbor = entries[neighbor_idx]
                        links.append({
                            "id": neighbor['id_hash'],
                            "title": neighbor['title'],
                            "score": float(D[idx][rank])
                        })

                entry['latent_connections'] = links[:5]
                updated_ledger.append(json.dumps(entry, ensure_ascii=False))

                dims = entry.get('vromlix_dimensions', {})
                narrative = dims.get('narrative', {}).get('narrative_context', '')[:100]

                writer.writerow([
                    entry['id_hash'][:8],
                    entry['origin_date'],
                    entry['assigned_category'],
                    entry['title'],
                    entry['executive_summary'],
                    narrative,
                    ";".join([l['title'] for l in links[:3]])
                ])

        # Write back to ledger with new connections
        with open(self.config.ledger_file, 'w', encoding='utf-8') as f:
            f.write('\n'.join(updated_ledger))
        logging.info("Indexing Complete.")


# ==============================================================================
# 5. ORCHESTRATOR & CLI
# ==============================================================================

class VromlixOrchestrator:
    def __init__(self, config: AppConfig):
        self.config = config
        self.config.ensure_directories()

        # Configure Logging
        logging.basicConfig(
            level=logging.INFO,
            format='%(asctime)s - [VROMLIX] - %(levelname)s - %(message)s',
            force=True
        )

    def run(self, stages: list[str]) -> None:
        logging.info(f"BOOTING VROMLIX {self.config.system_version}")

        # Mount Drive if Colab
        if Path("/content").exists() and not Path("/content/drive").exists():
            try:
                from google.colab import drive # type: ignore
                drive.mount("/content/drive")
            except ImportError: pass

        llm_client = GoogleGenAIAdapter(self.config)

        if "refinery" in stages:
            RefineryService(self.config, llm_client).process_inbox()

        if "mirror" in stages:
            MirrorService(self.config, llm_client).run_surgery()

        if "index" in stages:
            IndexingService(self.config).rebuild_index()

def main() -> None:
    parser = argparse.ArgumentParser(description="VROMLIX GENESIS: Cognitive Orchestrator")
    parser.add_argument("--run-all", action="store_true", help="Run full pipeline")
    parser.add_argument("--refinery", action="store_true", help="Run Ingestion only")
    parser.add_argument("--mirror", action="store_true", help="Run Profile Surgery only")
    parser.add_argument("--index", action="store_true", help="Run Indexing only")

    args = parser.parse_args([])

    # Default behavior if no args
    stages = []
    if args.run_all or (not any([args.refinery, args.mirror, args.index])):
        stages = ["refinery", "mirror", "index"]
    else:
        if args.refinery: stages.append("refinery")
        if args.mirror: stages.append("mirror")
        if args.index: stages.append("index")

    config = AppConfig()
    try:
        VromlixOrchestrator(config).run(stages)
    except Exception as e:
        logging.critical(f"SYSTEM HALT: {e}", exc_info=True)
        sys.exit(1)

if __name__ == "__main__":
    main()